---
title: "Clootrack Task"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(dplyr)
library(httr)
library(rjson)
```

Column {data-width=650}
-----------------------------------------------------------------------

###
Clootrack hiring Task. I make algorithm that take every data element from your provided API. After that identify graph type and plot the graph like below. Here I take default value for plot.

```{r}

dataAPI <- GET("https://s3-ap-southeast-1.amazonaws.com/he-public-data/chart2986176.json")

df <- as.list(fromJSON(rawToChar(dataAPI$content)))
  


mySolution <- function(i){

  
    tempdf <- as.data.frame(df[[i]]$elements)

   if(df[[i]]$type == 'Bar'){
    
    fig <- plot_ly(y = tempdf$`df[[1]]$elements`,color = tempdf$`df[[1]]$elements`,type = "bar")
    fig <- fig %>% layout(title = 'Interactive Bar Chart ',
    xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

    fig
  }else{
    tempdf <- as.data.frame(df[[1]]$elements)

    fig <- plot_ly(tempdf, labels = ~tempdf$`df[[1]]$elements`, values = ~tempdf$`df[[1]]$elements`, type = 'pie')
    fig <- fig %>% layout(title = 'Interactive Pie Chart ',
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
    fig
  }
  
  
}


mySolution(3)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Bar Chart

```{r}
print("Bar graph for first Element.")
dataAPI <- GET("https://s3-ap-southeast-1.amazonaws.com/he-public-data/chart2986176.json")

df <- rawToChar(dataAPI$content)
df <- as.list(fromJSON(rawToChar(dataAPI$content)))


tempdf <- as.data.frame(df[[1]]$elements)

fig <- plot_ly(y = tempdf$`df[[1]]$elements`,color = tempdf$`df[[1]]$elements`,type = "bar")
    fig <- fig %>% layout(title = 'Interactive Bar Chart ',
    xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

    fig

```

### Pie Chart

```{r}
print("Pie chart")
dataAPI <- GET("https://s3-ap-southeast-1.amazonaws.com/he-public-data/chart2986176.json")

df <- rawToChar(dataAPI$content)
df <- as.list(fromJSON(rawToChar(dataAPI$content)))


tempdf <- as.data.frame(df[[1]]$elements)

fig <- plot_ly(tempdf, labels = ~tempdf$`df[[1]]$elements`, values = ~tempdf$`df[[1]]$elements`, type = 'pie')
fig <- fig %>% layout(title = 'Interactive Pie Chart ',
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig

```

